import Head from "next/head";
import { Inter } from "next/font/google";
import StarsCanvas from "@/components/StarCanvas";
import Page2 from "@/components/Main/Page2";
import Services from "@/components/Main/OurServices";
import Testimonial from "@/components/Main/Review/Testimonial";
// import ClientScroll from "@/components/Main/Review/ClientScroll";
import WhyChooseUs from "@/components/Main/WhyChooseUs";
import ClientReview from "@/components/Main/Review/ClientReview";
import ScrollButton from "@/components/Main/ScrollButton";
import Banner from "@/components/Main/Banner";
// import BubbleEffect from "@/components/Main/BubbleEffect";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title> Moram Napu -- Gaming PR and Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
              (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "ipacudpt3c");
            `,
          }}
        />
      </Head>
      <main>
        {/* <StarsCanvas /> */}
        <Banner />
        <Page2 />
        <Services />
        <ClientReview />
        <Testimonial />
        {/* <ClientScroll /> */}
        <WhyChooseUs />
        <ScrollButton />
        {/* <BubbleEffect/>  */}
      </main>
    </>
  );
}
